#hello deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiaapp
  namespace: tiacourse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tiaapp
      run: tiaapp-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tiaapp
        run: tiaapp-service
    spec:
      containers:
        - name: tiaapp
          image: rahimflash/tiaapp:latest
          ports:
            - containerPort: 2024
              protocol: TCP
