#Write Me
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tiaapp
  namespace: tiacourse
spec:
  project: default
  source:
    repoURL: https://github.com/rahimflash/interviews.git   
    targetRevision: main
    path: /task/applications/argocd-app/argo-app.yaml
  destination:
    server: https://kubernetes.default.svc   
    namespace: tiacourse
  syncPolicy:
    automated:
      prune: true   
